In [1]:
import open3d as o3d
import cl
import utils as ut
import numpy as np
from skimage.morphology import binary_dilation
import proc3d
import json
from PIL import Image
from utils import *
import glob
import os
%matplotlib widget 
#%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt

In [7]:
class space_carving():
    def __init__(self, dataset_path):
        self.images = self.load_images(os.path.join(dataset_path, 'imgs'))
        self.extrinsics = self.load_extrinsics(os.path.join(dataset_path, 'extrinsics'))
        #self.bbox = json.load(open(os.path.join(dataset_path, 'bbox.json')))
        self.bbox = json.load(open(os.path.join(dataset_path, '/home/pico/uni/romi/scanner_cube/bbox_min_max.json')))
        
        self.camera_model = json.load(open(os.path.join(dataset_path, 'camera_model.json')))
        self.intrinsics= self.camera_model['params'][0:4]
        
        params = json.load(open(os.path.join(dataset_path, 'params.json')))
        self.gt=o3d.io.read_point_cloud(params["gt_path"])
        self.gt_points = np.asarray(self.gt.points)
        self.n_dilation=params["sc"]["n_dilation"]
        self.voxel_size = params['sc']['voxel_size']
        
        self.set_sc(self.bbox)
        
    def reset(self):
        del(self.sc)
        self.set_sc(self.bbox) 
        
    def load_extrinsics(self,path):
        ext = []
        ext_files = glob.glob(os.path.join(path, '*.json'))
        assert len(ext_files) != 0,"json list is empty."
        for i in sorted(ext_files):                                                                                                                                     
            ext.append(json.load(open(i)))                                                                                                                                                                                                                                                  
        return ext 
    
    def load_images(self,path):                                                                                                                                         
        imgs = []
        img_files = glob.glob(os.path.join(path, '*.png')) #get all .png files from folder path
        assert len(img_files) != 0,"Image list is empty."
        for i in sorted(img_files):                                                                                                                                     
            img = Image.open(i)                                                                                                                                      
            imgs.append(img.copy())                                                                                                                                     
            img.close()                                                                                                                                                                                                                                                   
        return imgs

    def set_sc(self,bbox):
        x_min, x_max = bbox['x']
        y_min, y_max = bbox['y']
        z_min, z_max = bbox['z']

        nx = int((x_max - x_min) / self.voxel_size) + 1
        ny = int((y_max - y_min) / self.voxel_size) + 1
        nz = int((z_max - z_min) / self.voxel_size) + 1
        
        print(nx,ny,nz)

        self.origin = np.array([x_min, y_min, z_min])
        self.sc = cl.Backprojection([nx, ny, nz], [x_min, y_min, z_min], self.voxel_size)

    def carve(self,idx):
        self.space_carve(self.images[idx], self.extrinsics[idx])
        
    def space_carve(self, im, rt):
        mask = get_mask(im)
        rot = sum(rt['R'], [])
        tvec = rt['T']
        if self.n_dilation:
            for k in range(self.n_dilation): mask = binary_dilation(mask)    
        self.sc.process_view(self.intrinsics, rot, tvec, mask)
        
    def dist_to_gt(self):
        vol = self.sc.values().copy()
        vol = vol.reshape(self.sc.shape)
        pcd=proc3d.vol2pcd_exp(vol, self.origin, self.voxel_size, level_set_value=0) 
        pcd_p = np.asarray(pcd.points)
        cd=chamfer_d(self.gt_points , pcd_p)
        return cd

In [8]:
class space_carving_2():
    def __init__(self, dataset_path):
        self.img_files = sorted (glob.glob(os.path.join(dataset_path, 'imgs', '*.png')) )#get all .png file names from folder path
        self.extrinsics = self.load_extrinsics(os.path.join(dataset_path, 'extrinsics'))
        #self.bbox = json.load(open(os.path.join(dataset_path, 'bbox.json')))
        self.bbox = json.load(open(os.path.join(dataset_path, '/home/pico/uni/romi/scanner_cube/bbox_min_max.json')))
        self.camera_model = json.load(open(os.path.join(dataset_path, 'camera_model.json')))
        self.intrinsics= self.camera_model['params'][0:4]
        
        params = json.load(open(os.path.join(dataset_path, 'params.json')))
        self.gt=o3d.io.read_point_cloud(params["gt_path"])
        self.gt_points = np.asarray(self.gt.points)
        self.n_dilation=params["sc"]["n_dilation"]
        self.voxel_size = params['sc']['voxel_size']
        
        self.set_sc(self.bbox)
        
    def reset(self):
        del(self.sc)
        self.set_sc(self.bbox) 
        
    def load_extrinsics(self,path):
        ext = []
        ext_files = glob.glob(os.path.join(path, '*.json'))
        assert len(ext_files) != 0,"json list is empty."
        for i in sorted(ext_files):                                                                                                                                     
            ext.append(json.load(open(i)))                                                                                                                                                                                                                                                  
        return ext 
    
    def load_image(self,idx):                                                                                                                                         
        img = Image.open(self.img_files[idx])                                                                                                                                      
        cp = img.copy()                                                                                                                                 
        img.close()                                                                                                                                                                                                                                                   
        return cp

    def set_sc(self,bbox):
        x_min, x_max = bbox['x']
        y_min, y_max = bbox['y']
        z_min, z_max = bbox['z']

        nx = int((x_max - x_min) / self.voxel_size) + 1
        ny = int((y_max - y_min) / self.voxel_size) + 1
        nz = int((z_max - z_min) / self.voxel_size) + 1

        self.origin = np.array([x_min, y_min, z_min])
        self.sc = cl.Backprojection([nx, ny, nz], [x_min, y_min, z_min], self.voxel_size)

    def carve(self,idx):
        im = self.load_image(idx)
        self.space_carve(im, self.extrinsics[idx])
        
    def space_carve(self, im, rt):
        mask = get_mask(im)
        rot = sum(rt['R'], [])
        tvec = rt['T']
        if self.n_dilation:
            for k in range(self.n_dilation): mask = binary_dilation(mask)    
        self.sc.process_view(self.intrinsics, rot, tvec, mask)
        
    def dist_to_gt(self):
        vol = self.sc.values().copy()
        vol = vol.reshape(self.sc.shape)
        pcd=proc3d.vol2pcd_exp(vol, self.origin, self.voxel_size, level_set_value=0) 
        pcd_p = np.asarray(pcd.points)
        cd=chamfer_d(self.gt_points , pcd_p)
        return cd

In [2]:
class space_carving_2_masks():
    def __init__(self, dataset_path):
        self.masks_files = sorted (glob.glob(os.path.join(dataset_path, 'masks', '*.png')) )#get all .png file names from folder path
        self.extrinsics = self.load_extrinsics(os.path.join(dataset_path, 'extrinsics'))
        #self.bbox = json.load(open(os.path.join(dataset_path, 'bbox.json')))
        self.bbox = json.load(open(os.path.join(dataset_path, '/home/pico/uni/romi/scanner_cube/bbox_min_max.json')))
        self.camera_model = json.load(open(os.path.join(dataset_path, 'camera_model.json')))
        self.intrinsics= self.camera_model['params'][0:4]
        
        params = json.load(open(os.path.join(dataset_path, 'params.json')))
        #self.gt=o3d.io.read_point_cloud(params["gt_path"])
        #self.gt_points = np.asarray(self.gt.points)
        self.n_dilation=params["sc"]["n_dilation"]
        self.voxel_size = params['sc']['voxel_size']
        
        self.set_sc(self.bbox)
        
    def reset(self):
        del(self.sc)
        self.set_sc(self.bbox) 
        
    def load_extrinsics(self,path):
        ext = []
        ext_files = glob.glob(os.path.join(path, '*.json'))
        assert len(ext_files) != 0,"json list is empty."
        for i in sorted(ext_files):                                                                                                                                     
            ext.append(json.load(open(i)))                                                                                                                                                                                                                                                  
        return ext 
    
    def load_mask(self,idx):                                                                                                                                         
        img = cv2.imread(self.masks_files[idx], cv2.IMREAD_GRAYSCALE)                                                                                                                                                                                                                                                                                                                                                                                     
        return img

    def set_sc(self,bbox):
        x_min, x_max = bbox['x']
        y_min, y_max = bbox['y']
        z_min, z_max = bbox['z']

        nx = int((x_max - x_min) / self.voxel_size) + 1
        ny = int((y_max - y_min) / self.voxel_size) + 1
        nz = int((z_max - z_min) / self.voxel_size) + 1

        self.origin = np.array([x_min, y_min, z_min])
        self.sc = cl.Backprojection([nx, ny, nz], [x_min, y_min, z_min], self.voxel_size)

    def carve(self,idx):
        im = self.load_mask(idx)
        self.space_carve(im, self.extrinsics[idx])
        
    def space_carve(self, mask, rt):
        #mask = im.copy() #get_mask(im)
        rot = sum(rt['R'], [])
        tvec = rt['T']
        if self.n_dilation:
            for k in range(self.n_dilation): mask = binary_dilation(mask)    
        self.sc.process_view(self.intrinsics, rot, tvec, mask)
        
    '''def dist_to_gt(self):
        vol = self.sc.values().copy()
        vol = vol.reshape(self.sc.shape)
        pcd=proc3d.vol2pcd_exp(vol, self.origin, self.voxel_size, level_set_value=0) 
        pcd_p = np.asarray(pcd.points)
        cd=chamfer_d(self.gt_points , pcd_p)
        return cd'''


In [18]:
#data_path = '/home/pico/uni/romi/scanner_cube/arabidopsis_im_bigger/000'
#spc = space_carving(data_path)

#for i in range(180):
#    spc.carve(i)

# for creating a responsive plot
%matplotlib widget
  
# importing required libraries
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
  
x,y,z = np.where(spc.sc.values()[:64,:64,:128]==1)
  
# creating figure
fig = plt.figure()
ax = Axes3D(fig)

ax.set_xlim3d(0, 64)
ax.set_ylim3d(0, 64)
ax.set_zlim3d(0, 128)

#ax.set_xlim3d(0, 140)
#ax.set_ylim3d(0, 140)
#ax.set_zlim3d(0, 140)
  
# creating the plot
plot_geeks = ax.scatter(x, y, z, color='green',s=1)

x,y,z = np.where(spc.sc.values()==0)
#plot_geeks = ax.scatter(x, y, z, color='red',s=1)
  
# setting title and labels
ax.set_title("3D plot")
ax.set_xlabel('x-axis')
ax.set_ylabel('y-axis')
ax.set_zlabel('z-axis')
ax.grid()
  
# displaying the plot
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [ ]:
np.histogram(spc.sc.values(), bins=3)

In [16]:
data_path = '/home/pico/uni/romi/scanner_cube/arabidopsis_im_bigger/204'#'
spc = space_carving_2_masks(data_path)

In [ ]:
spc.carve(45)
print(np.histogram(spc.sc.values(), bins=3)[0])

In [ ]:
print(np.histogram(spc.sc.values(), bins=3)[0])

In [ ]:
ant = 0
for i in range(0,180,40):
    spc.carve(i)
    h = np.histogram(spc.sc.values(), bins=3)
    print(i,h[0],h[0][0]-ant)
    ant=h[0][0]

In [17]:

pos = np.random.randint(180, size=10)
for i in range(180):#pos:
    spc.carve(i)
    print(i,np.histogram(spc.sc.values(), bins=3)[0])


0 [395109 177999 109068]
1 [401372 177347 103457]
2 [405121 176853 100202]
3 [408838 176336  97002]
4 [412852 175710  93614]
5 [417207 175063  89906]
6 [421805 174403  85968]
7 [426864 173684  81628]
8 [431724 172998  77454]
9 [435703 172204  74269]
10 [440022 171372  70782]
11 [442541 170608  69027]
12 [444887 169782  67507]
13 [447230 168870  66076]
14 [449857 168009  64310]
15 [451509 167090  63577]
16 [452835 166167  63174]
17 [454636 165190  62350]
18 [456058 164229  61889]
19 [457597 163273  61306]
20 [459011 162313  60852]
21 [460459 161278  60439]
22 [461766 160367  60043]
23 [463308 159275  59593]
24 [464943 158168  59065]
25 [466206 157308  58662]
26 [467635 156291  58250]
27 [468937 155276  57963]
28 [470059 154312  57805]
29 [471731 153309  57136]
30 [473058 152341  56777]
31 [474272 151349  56555]
32 [475812 150348  56016]
33 [477027 149384  55765]
34 [478291 148399  55486]
35 [479667 147400  55109]
36 [481071 146419  54686]
37 [482401 145446  54329]
38 [483709 144447  540

In [ ]:
spc.sc.values().shape

In [ ]:
#data_path = '/home/pico/uni/romi/scanner_cube/arabidopsis_im_bigger/'
data_path = '/home/pico/uni/romi/rl_sony/arabidopsis_image_sets'
gdeltas = []
for plantn in [202]:#range(180):
    spc = space_carving_2(os.path.join(data_path,str(plantn).zfill(3)))
    for i in range(180):
        deltas = []
        pos = np.random.randint(180, size=10)
        n_ant = 0
        for p in pos:
            spc.carve(p)
            espaces = np.histogram(spc.sc.values(), bins=3)[0][0]
            delta = espaces-n_ant
            deltas.append(delta)
            n_ant = espaces
        print(deltas)
        gdeltas.append(deltas)

In [21]:
data =[]
for bias in range(180):
    data_path = '/home/pico/uni/romi/scanner_cube/arabidopsis_im_bigger/204'
    spc = space_carving_2_masks(data_path)
    for i in range(0,180,10):
        spc.carve(calculate_position(i,bias))
    h = np.histogram(spc.sc.values(), bins=3)[0]
    data.append(h)
    print(bias,h)

print(np.mean(data,axis=0))

0 [626601  11215  44360]
1 [626418  11216  44542]
2 [628229  11210  42737]
3 [629678  11208  41290]
4 [628930  11219  42027]
5 [628003  11229  42944]
6 [629223  11225  41728]
7 [629897  11223  41056]
8 [629682  11218  41276]
9 [629757  11220  41199]
10 [626601  11215  44360]
11 [626418  11216  44542]
12 [628229  11210  42737]
13 [629678  11208  41290]
14 [628930  11219  42027]
15 [628003  11229  42944]
16 [629223  11225  41728]
17 [629897  11223  41056]
18 [629682  11218  41276]
19 [629757  11220  41199]
20 [626601  11215  44360]
21 [626418  11216  44542]
22 [628229  11210  42737]
23 [629678  11208  41290]
24 [628930  11219  42027]
25 [628003  11229  42944]
26 [629223  11225  41728]
27 [629897  11223  41056]
28 [629682  11218  41276]
29 [629757  11220  41199]
30 [626601  11215  44360]
31 [626418  11216  44542]
32 [628229  11210  42737]
33 [629678  11208  41290]
34 [628930  11219  42027]
35 [628003  11229  42944]
36 [629223  11225  41728]
37 [629897  11223  41056]
38 [629682  11218  412

In [ ]:
dt = np.array(gdeltas)

In [ ]:
dt.shape

In [22]:
data =[]
for n in range(180):
    data_path = '/home/pico/uni/romi/scanner_cube/arabidopsis_im_bigger/204'
    spc = space_carving_2_masks(data_path)
    pos = np.random.randint(180, size=18)
    for i in pos:
        spc.carve(i)
    h = np.histogram(spc.sc.values(), bins=3)[0]
    data.append(h)
    print(h)

print(np.mean(data,axis=0))

[617096  12367  52713]
[617250  11747  53179]
[627924  11369  42883]
[621568  11561  49047]
[632480  11414  38282]
[631326  11335  39515]
[628576  11470  42130]
[626794  11656  43726]
[629157  11692  41327]
[617627  12265  52284]
[603710  11870  66596]
[617024  12008  53144]
[624652  12398  45126]
[627197  11545  43434]
[622260  11399  48517]
[618488  12459  51229]
[623949  11468  46759]
[627823  11436  42917]
[622019  11487  48670]
[619089  11359  51728]
[630199  11497  40480]
[629490  11621  41065]
[619368  11579  51229]
[620102  12550  49524]
[626514  11481  44181]
[607229  13789  61158]
[625852  12392  43932]
[620274  11971  49931]
[622398  11448  48330]
[626854  12242  43080]
[622952  11556  47668]
[628466  11491  42219]
[624183  11524  46469]
[633119  11638  37419]
[606946  12029  63201]
[608881  11457  61838]
[619234  12226  50716]
[631637  11492  39047]
[622741  11633  47802]
[610021  11654  60501]
[620471  11643  50062]
[626376  11538  44262]
[600725  11817  69634]
[628203  11

In [ ]:
np.mean(dt,axis=0)

In [ ]:
np.min(dt,axis=0)

In [ ]:
np.max(dt,axis=0)

In [ ]:
np.std(dt,axis=0)

In [13]:
def calculate_position(init_state,steps):
        n_positions = 180
        n_pos = init_state + steps
        if n_pos>(n_positions-1):
            n_pos -= n_positions
        elif n_pos<0:
            n_pos += n_positions
        return n_pos

In [ ]:
rel_pos = 0
p_bias = 179
abs_pos = calculate_position(rel_pos,p_bias)
print(abs_pos)

In [ ]:
spc.sc.values().shape

In [5]:
spc.sc.values().shape

(66, 68, 152)

In [6]:
66*68*152

682176