In [4]:
import open3d as o3d
import cl
import utils as ut
import numpy as np
from skimage.morphology import binary_dilation
import proc3d
import json
from PIL import Image
from utils import *
import glob
import os
%matplotlib widget 
#%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
import glob

In [7]:
class space_carving():
    def __init__(self, dataset_path):
        self.images = self.load_images(os.path.join(dataset_path, 'imgs'))
        self.extrinsics = self.load_extrinsics(os.path.join(dataset_path, 'extrinsics'))
        #self.bbox = json.load(open(os.path.join(dataset_path, 'bbox.json')))
        self.bbox = json.load(open(os.path.join(dataset_path, '/home/pico/uni/romi/scanner_cube/bbox_min_max.json')))
        
        self.camera_model = json.load(open(os.path.join(dataset_path, 'camera_model.json')))
        self.intrinsics= self.camera_model['params'][0:4]
        
        params = json.load(open(os.path.join(dataset_path, 'params.json')))
        self.gt=o3d.io.read_point_cloud(params["gt_path"])
        self.gt_points = np.asarray(self.gt.points)
        self.n_dilation=params["sc"]["n_dilation"]
        self.voxel_size = params['sc']['voxel_size']
        
        self.set_sc(self.bbox)
        
    def reset(self):
        del(self.sc)
        self.set_sc(self.bbox) 
        
    def load_extrinsics(self,path):
        ext = []
        ext_files = glob.glob(os.path.join(path, '*.json'))
        assert len(ext_files) != 0,"json list is empty."
        for i in sorted(ext_files):                                                                                                                                     
            ext.append(json.load(open(i)))                                                                                                                                                                                                                                                  
        return ext 
    
    def load_images(self,path):                                                                                                                                         
        imgs = []
        img_files = glob.glob(os.path.join(path, '*.png')) #get all .png files from folder path
        assert len(img_files) != 0,"Image list is empty."
        for i in sorted(img_files):                                                                                                                                     
            img = Image.open(i)                                                                                                                                      
            imgs.append(img.copy())                                                                                                                                     
            img.close()                                                                                                                                                                                                                                                   
        return imgs

    def set_sc(self,bbox):
        x_min, x_max = bbox['x']
        y_min, y_max = bbox['y']
        z_min, z_max = bbox['z']

        nx = int((x_max - x_min) / self.voxel_size) + 1
        ny = int((y_max - y_min) / self.voxel_size) + 1
        nz = int((z_max - z_min) / self.voxel_size) + 1
        
        print(nx,ny,nz)

        self.origin = np.array([x_min, y_min, z_min])
        self.sc = cl.Backprojection([nx, ny, nz], [x_min, y_min, z_min], self.voxel_size)

    def carve(self,idx):
        self.space_carve(self.images[idx], self.extrinsics[idx])
        
    def space_carve(self, im, rt):
        mask = get_mask(im)
        rot = sum(rt['R'], [])
        tvec = rt['T']
        if self.n_dilation:
            for k in range(self.n_dilation): mask = binary_dilation(mask)    
        self.sc.process_view(self.intrinsics, rot, tvec, mask)
        
    def dist_to_gt(self):
        vol = self.sc.values().copy()
        vol = vol.reshape(self.sc.shape)
        pcd=proc3d.vol2pcd_exp(vol, self.origin, self.voxel_size, level_set_value=0) 
        pcd_p = np.asarray(pcd.points)
        cd=chamfer_d(self.gt_points , pcd_p)
        return cd

In [3]:
class space_carving_2():
    def __init__(self, dataset_path):
        self.img_files = sorted (glob.glob(os.path.join(dataset_path, 'imgs', '*.png')) )#get all .png file names from folder path
        self.extrinsics = self.load_extrinsics(os.path.join(dataset_path, 'extrinsics'))
        #self.bbox = json.load(open(os.path.join(dataset_path, 'bbox.json')))
        self.bbox = json.load(open(os.path.join(dataset_path, '/home/pico/uni/romi/scanner_cube/bbox_min_max.json')))
        self.camera_model = json.load(open(os.path.join(dataset_path, 'camera_model.json')))
        self.intrinsics= self.camera_model['params'][0:4]
        
        params = json.load(open(os.path.join(dataset_path, 'params.json')))
        self.gt=o3d.io.read_point_cloud(params["gt_path"])
        self.gt_points = np.asarray(self.gt.points)
        self.n_dilation=params["sc"]["n_dilation"]
        self.voxel_size = params['sc']['voxel_size']
        
        self.set_sc(self.bbox)
        
    def reset(self):
        del(self.sc)
        self.set_sc(self.bbox) 
        
    def load_extrinsics(self,path):
        ext = []
        ext_files = glob.glob(os.path.join(path, '*.json'))
        assert len(ext_files) != 0,"json list is empty."
        for i in sorted(ext_files):                                                                                                                                     
            ext.append(json.load(open(i)))                                                                                                                                                                                                                                                  
        return ext 
    
    def load_image(self,idx):                                                                                                                                         
        img = Image.open(self.img_files[idx])                                                                                                                                      
        cp = img.copy()                                                                                                                                 
        img.close()                                                                                                                                                                                                                                                   
        return cp

    def set_sc(self,bbox):
        x_min, x_max = bbox['x']
        y_min, y_max = bbox['y']
        z_min, z_max = bbox['z']

        nx = int((x_max - x_min) / self.voxel_size) + 1
        ny = int((y_max - y_min) / self.voxel_size) + 1
        nz = int((z_max - z_min) / self.voxel_size) + 1

        self.origin = np.array([x_min, y_min, z_min])
        self.sc = cl.Backprojection([nx, ny, nz], [x_min, y_min, z_min], self.voxel_size)

    def carve(self,idx):
        im = self.load_image(idx)
        self.space_carve(im, self.extrinsics[idx])
        
    def space_carve(self, im, rt):
        mask = get_mask(im)
        rot = sum(rt['R'], [])
        tvec = rt['T']
        if self.n_dilation:
            for k in range(self.n_dilation): mask = binary_dilation(mask)    
        self.sc.process_view(self.intrinsics, rot, tvec, mask)
        
    def dist_to_gt(self):
        vol = self.sc.values().copy()
        vol = vol.reshape(self.sc.shape)
        pcd=proc3d.vol2pcd_exp(vol, self.origin, self.voxel_size, level_set_value=0) 
        pcd_p = np.asarray(pcd.points)
        cd=chamfer_d(self.gt_points , pcd_p)
        return cd

In [5]:
class space_carving_2_masks():
    def __init__(self, dataset_path,gt_mode=False):
        self.masks_files = sorted (glob.glob(os.path.join(dataset_path, 'masks', '*.png')) )#get all .png file names from folder path
        self.extrinsics = self.load_extrinsics(os.path.join(dataset_path, 'extrinsics'))
        #self.bbox = json.load(open(os.path.join(dataset_path, 'bbox.json')))
        self.bbox = json.load(open(os.path.join(dataset_path, '/home/pico/uni/romi/scanner_cube/bbox_min_max.json')))
        self.camera_model = json.load(open(os.path.join(dataset_path, 'camera_model.json')))
        self.intrinsics= self.camera_model['params'][0:4]
        
        params = json.load(open(os.path.join(dataset_path, 'params.json')))


        #self.gt=o3d.io.read_point_cloud(params["gt_path"])
        #self.gt_points = np.asarray(self.gt.points)
        self.gt_mode = gt_mode

        if self.gt_mode is True:
            self.gt = np.load(os.path.join(dataset_path, 'volumes','vol_180.npy'))
            self.gt_solid_mask = np.where(self.gt==1,True,False) 
            self.gt_n_solid_voxels = np.count_nonzero(self.gt_solid_mask)


        self.n_dilation=params["sc"]["n_dilation"]
        self.voxel_size = params['sc']['voxel_size']
        
        self.set_sc(self.bbox)
        
    def reset(self):
        del(self.sc)
        self.set_sc(self.bbox) 
        
    def load_extrinsics(self,path):
        ext = []
        ext_files = glob.glob(os.path.join(path, '*.json'))
        assert len(ext_files) != 0,"json list is empty."
        for i in sorted(ext_files):                                                                                                                                     
            ext.append(json.load(open(i)))                                                                         
        return ext 
    
    def load_mask(self,idx):                                                                                                                                         
        img = cv2.imread(self.masks_files[idx], cv2.IMREAD_GRAYSCALE)
        return img

    def set_sc(self,bbox):
        x_min, x_max = bbox['x']
        y_min, y_max = bbox['y']
        z_min, z_max = bbox['z']

        nx = int((x_max - x_min) / self.voxel_size) + 1
        ny = int((y_max - y_min) / self.voxel_size) + 1
        nz = int((z_max - z_min) / self.voxel_size) + 1

        self.origin = np.array([x_min, y_min, z_min])
        self.sc = cl.Backprojection([nx, ny, nz], [x_min, y_min, z_min], self.voxel_size)

    def carve(self,idx):
        im = self.load_mask(idx)
        self.space_carve(im, self.extrinsics[idx])
        
    def space_carve(self, mask, rt):
        #mask = im.copy() #get_mask(im)
        rot = sum(rt['R'], [])
        tvec = rt['T']
        if self.n_dilation:
            for k in range(self.n_dilation): mask = binary_dilation(mask)    
        self.sc.process_view(self.intrinsics, rot, tvec, mask)


    def gt_compare(self,test_vol):
        if self.gt_mode is False:
            return 0
        #compare current volume with ground truth (voxelwise) and return percentage
        comp = np.where( self.gt==test_vol,True,False)
        eq_count = np.count_nonzero(comp)
        #perc_sim = (eq_count/np.prod(gt_vol.shape) )*100.
        #perc_sim = (eq_count/682176)*100. #682176number of voxels of the volumes used here 
        perc_sim = eq_count * 0.00014658973637301812
        return perc_sim
    
    def gt_compare_solid(self,test_vol):
        if self.gt_mode is False:
            return 0
        #compares only solid voxels (with 1;s) between ground truth and test_vol  
        vol_solid_mask = np.where(test_vol==1,True,False) 
        vol_n_solid_voxels = np.count_nonzero(vol_solid_mask)
        intersection = self.gt_solid_mask & vol_solid_mask
        n_intersection = np.count_nonzero(intersection)
        ratio = n_intersection / ( self.gt_n_solid_voxels + vol_n_solid_voxels - n_intersection )
        return ratio
    
    '''def dist_to_gt(self):
        vol = self.sc.values().copy()
        vol = vol.reshape(self.sc.shape)
        pcd=proc3d.vol2pcd_exp(vol, self.origin, self.voxel_size, level_set_value=0) 
        pcd_p = np.asarray(pcd.points)
        cd=chamfer_d(self.gt_points , pcd_p)
        return cd'''


In [18]:
#data_path = '/home/pico/uni/romi/scanner_cube/arabidopsis_im_bigger/000'
#spc = space_carving(data_path)

#for i in range(180):
#    spc.carve(i)

# for creating a responsive plot
%matplotlib widget
  
# importing required libraries
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
  
x,y,z = np.where(spc.sc.values()[:64,:64,:128]==1)
  
# creating figure
fig = plt.figure()
ax = Axes3D(fig)

ax.set_xlim3d(0, 64)
ax.set_ylim3d(0, 64)
ax.set_zlim3d(0, 128)

#ax.set_xlim3d(0, 140)
#ax.set_ylim3d(0, 140)
#ax.set_zlim3d(0, 140)
  
# creating the plot
plot_geeks = ax.scatter(x, y, z, color='green',s=1)

x,y,z = np.where(spc.sc.values()==0)
#plot_geeks = ax.scatter(x, y, z, color='red',s=1)
  
# setting title and labels
ax.set_title("3D plot")
ax.set_xlabel('x-axis')
ax.set_ylabel('y-axis')
ax.set_zlabel('z-axis')
ax.grid()
  
# displaying the plot
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [ ]:
np.histogram(spc.sc.values(), bins=3)

In [16]:
data_path = '/home/pico/uni/romi/scanner_cube/arabidopsis_im_bigger/204'#'
spc = space_carving_2_masks(data_path)

In [ ]:
spc.carve(45)
print(np.histogram(spc.sc.values(), bins=3)[0])

In [ ]:
print(np.histogram(spc.sc.values(), bins=3)[0])

In [ ]:
ant = 0
for i in range(0,180,40):
    spc.carve(i)
    h = np.histogram(spc.sc.values(), bins=3)
    print(i,h[0],h[0][0]-ant)
    ant=h[0][0]

In [17]:

pos = np.random.randint(180, size=10)
for i in range(180):#pos:
    spc.carve(i)
    print(i,np.histogram(spc.sc.values(), bins=3)[0])


0 [395109 177999 109068]
1 [401372 177347 103457]
2 [405121 176853 100202]
3 [408838 176336  97002]
4 [412852 175710  93614]
5 [417207 175063  89906]
6 [421805 174403  85968]
7 [426864 173684  81628]
8 [431724 172998  77454]
9 [435703 172204  74269]
10 [440022 171372  70782]
11 [442541 170608  69027]
12 [444887 169782  67507]
13 [447230 168870  66076]
14 [449857 168009  64310]
15 [451509 167090  63577]
16 [452835 166167  63174]
17 [454636 165190  62350]
18 [456058 164229  61889]
19 [457597 163273  61306]
20 [459011 162313  60852]
21 [460459 161278  60439]
22 [461766 160367  60043]
23 [463308 159275  59593]
24 [464943 158168  59065]
25 [466206 157308  58662]
26 [467635 156291  58250]
27 [468937 155276  57963]
28 [470059 154312  57805]
29 [471731 153309  57136]
30 [473058 152341  56777]
31 [474272 151349  56555]
32 [475812 150348  56016]
33 [477027 149384  55765]
34 [478291 148399  55486]
35 [479667 147400  55109]
36 [481071 146419  54686]
37 [482401 145446  54329]
38 [483709 144447  540

In [ ]:
spc.sc.values().shape

In [ ]:
#data_path = '/home/pico/uni/romi/scanner_cube/arabidopsis_im_bigger/'
data_path = '/home/pico/uni/romi/rl_sony/arabidopsis_image_sets'
gdeltas = []
for plantn in [202]:#range(180):
    spc = space_carving_2(os.path.join(data_path,str(plantn).zfill(3)))
    for i in range(180):
        deltas = []
        pos = np.random.randint(180, size=10)
        n_ant = 0
        for p in pos:
            spc.carve(p)
            espaces = np.histogram(spc.sc.values(), bins=3)[0][0]
            delta = espaces-n_ant
            deltas.append(delta)
            n_ant = espaces
        print(deltas)
        gdeltas.append(deltas)

In [21]:
data =[]
for bias in range(180):
    data_path = '/home/pico/uni/romi/scanner_cube/arabidopsis_im_bigger/204'
    spc = space_carving_2_masks(data_path)
    for i in range(0,180,10):
        spc.carve(calculate_position(i,bias))
    h = np.histogram(spc.sc.values(), bins=3)[0]
    data.append(h)
    print(bias,h)

print(np.mean(data,axis=0))

0 [626601  11215  44360]
1 [626418  11216  44542]
2 [628229  11210  42737]
3 [629678  11208  41290]
4 [628930  11219  42027]
5 [628003  11229  42944]
6 [629223  11225  41728]
7 [629897  11223  41056]
8 [629682  11218  41276]
9 [629757  11220  41199]
10 [626601  11215  44360]
11 [626418  11216  44542]
12 [628229  11210  42737]
13 [629678  11208  41290]
14 [628930  11219  42027]
15 [628003  11229  42944]
16 [629223  11225  41728]
17 [629897  11223  41056]
18 [629682  11218  41276]
19 [629757  11220  41199]
20 [626601  11215  44360]
21 [626418  11216  44542]
22 [628229  11210  42737]
23 [629678  11208  41290]
24 [628930  11219  42027]
25 [628003  11229  42944]
26 [629223  11225  41728]
27 [629897  11223  41056]
28 [629682  11218  41276]
29 [629757  11220  41199]
30 [626601  11215  44360]
31 [626418  11216  44542]
32 [628229  11210  42737]
33 [629678  11208  41290]
34 [628930  11219  42027]
35 [628003  11229  42944]
36 [629223  11225  41728]
37 [629897  11223  41056]
38 [629682  11218  412

In [ ]:
dt = np.array(gdeltas)

In [ ]:
dt.shape

In [22]:
data =[]
for n in range(180):
    data_path = '/home/pico/uni/romi/scanner_cube/arabidopsis_im_bigger/204'
    spc = space_carving_2_masks(data_path)
    pos = np.random.randint(180, size=18)
    for i in pos:
        spc.carve(i)
    h = np.histogram(spc.sc.values(), bins=3)[0]
    data.append(h)
    print(h)

print(np.mean(data,axis=0))

[617096  12367  52713]
[617250  11747  53179]
[627924  11369  42883]
[621568  11561  49047]
[632480  11414  38282]
[631326  11335  39515]
[628576  11470  42130]
[626794  11656  43726]
[629157  11692  41327]
[617627  12265  52284]
[603710  11870  66596]
[617024  12008  53144]
[624652  12398  45126]
[627197  11545  43434]
[622260  11399  48517]
[618488  12459  51229]
[623949  11468  46759]
[627823  11436  42917]
[622019  11487  48670]
[619089  11359  51728]
[630199  11497  40480]
[629490  11621  41065]
[619368  11579  51229]
[620102  12550  49524]
[626514  11481  44181]
[607229  13789  61158]
[625852  12392  43932]
[620274  11971  49931]
[622398  11448  48330]
[626854  12242  43080]
[622952  11556  47668]
[628466  11491  42219]
[624183  11524  46469]
[633119  11638  37419]
[606946  12029  63201]
[608881  11457  61838]
[619234  12226  50716]
[631637  11492  39047]
[622741  11633  47802]
[610021  11654  60501]
[620471  11643  50062]
[626376  11538  44262]
[600725  11817  69634]
[628203  11

In [ ]:
np.mean(dt,axis=0)

In [ ]:
np.min(dt,axis=0)

In [ ]:
np.max(dt,axis=0)

In [ ]:
np.std(dt,axis=0)

In [8]:
def calculate_position(init_state,steps):
        n_positions = 180
        n_pos = init_state + steps
        if n_pos>(n_positions-1):
            n_pos -= n_positions
        elif n_pos<0:
            n_pos += n_positions
        return n_pos

In [ ]:
rel_pos = 0
p_bias = 179
abs_pos = calculate_position(rel_pos,p_bias)
print(abs_pos)

In [ ]:
spc.sc.values().shape

In [5]:
spc.sc.values().shape

(66, 68, 152)

In [6]:
66*68*152

682176

In [23]:
def test_uniform(data_path,n_images):
    data =[]
    for bias in range(180):
        spc = space_carving_2_masks(data_path)
        dist = 180//n_images
        for i in range(0,180,dist):
            spc.carve(calculate_position(i,bias))
        h = np.histogram(spc.sc.values(), bins=3)[0]
        data.append(h)
        print(bias,h)
    return data

def test_random(data_path,n_images):
    data =[]
    for n in range(180):
        spc = space_carving_2_masks(data_path)
        pos = np.random.randint(180, size=n_images)
        for i in pos:
            spc.carve(i)
        h = np.histogram(spc.sc.values(), bins=3)[0]
        data.append(h)
        print(h)
    return data

def test_all(data_path):
    spc = space_carving_2_masks(data_path)
    for i in range(180):#pos:
        spc.carve(i)
        count = np.histogram(spc.sc.values(), bins=3)[0]
        print(i,count)
    return count

In [6]:
def compare_vols(gt_vol,test_vol):
    comp = np.where( gt_vol==test_vol,True,False)
    eq_count = np.count_nonzero(comp)
    #perc_sim = (eq_count/np.prod(gt_vol.shape) )*100.
    #perc_sim = (eq_count/682176)*100. #682176number of voxels of the volumes used here 
    perc_sim = eq_count * 0.00014658973637301812
    return perc_sim 

def test_uniform(data_path,n_images):
    data =[]
    gt_dist = []
    for bias in range(180):
        spc = space_carving_2_masks(data_path,gt_mode=True)
        dist = 180//n_images
        for i in range(0,180,dist):
            spc.carve(calculate_position(i,bias))
        gt_sim = spc.gt_compare_solid(spc.sc.values())
        gt_dist.append(gt_sim)
        h = np.histogram(spc.sc.values(), bins=3)[0]
        data.append(h)
        print(bias,h,gt_sim)
    return data,gt_dist

def test_random(data_path,n_images):
    data =[]
    gt_dist = []
    for n in range(180):
        spc = space_carving_2_masks(data_path,gt_mode=True)
        pos = np.random.randint(180, size=n_images)
        for i in pos:
            spc.carve(i)
        gt_sim = spc.gt_compare_solid(spc.sc.values())
        gt_dist.append(gt_sim)
        h = np.histogram(spc.sc.values(), bins=3)[0]
        data.append(h)
        print(h,gt_sim)
    return data,gt_dist

def test_all(data_path):
    spc = space_carving_2_masks(data_path)
    for i in range(180):#pos:
        spc.carve(i)
        count = np.histogram(spc.sc.values(), bins=3)[0]
        print(i,count)
    return count

In [15]:
data_path = '/home/pico/uni/romi/scanner_cube/arabidopsis_im_bigger/000'
#print('count_rand: mean ',np.mean(count_rand,axis=0), ' std ',np.std(count_rand,axis=0) )
#print('count_uni', np.mean(count_uni,axis=0), ' std ',np.std(count_uni,axis=0) )
#print('count_all',count_all)

count_rand,dist_rand = test_random(data_path,10)
count_uni, dist_uni = test_uniform(data_path,10)
count_all = test_all(data_path)

print('count_rand',np.mean(count_rand,axis=0),np.mean(dist_rand))
print('count_uni', np.mean(count_uni,axis=0),np.mean(dist_uni))
print('count_all',count_all)

[666107  11763   4306] 0.5512999071494893
[665959  11901   4316] 0.5500231588698472
[663973  12553   5650] 0.420205237084218
[664160  12725   5291] 0.44870583789911206
[665065  12463   4648] 0.510752688172043
[664396  12231   5549] 0.42785083768690324
[655887  17778   8511] 0.25756525756525755
[662941  13064   6171] 0.38473999676008425
[666226  11893   4057] 0.585119487558512
[665922  12036   4218] 0.5627962085308057
[661694  14350   6132] 0.3871861754157157
[662340  12568   7268] 0.3255909840571743
[665136  12496   4544] 0.5224373075230972
[663919  12859   5398] 0.4398148148148148
[661813  13859   6504] 0.36504764832462344
[664629  12443   5104] 0.4651390520955738
[663708  12532   5936] 0.40020212228398183
[649275  22375  10526] 0.22558890577507598
[664667  12452   5057] 0.4694603676615932
[664063  13728   4385] 0.541372236152268
[663655  12745   5776] 0.41104188300449984
[660659  13135   8382] 0.2832776717557252
[661047  14535   6594] 0.36027293404094013
[666027  11908   4241] 0.5597

14 [666981  11477   3718] 0.6384408602150538
15 [667052  11472   3652] 0.6499726327312534
16 [667053  11466   3657] 0.6490844493030883
17 [667098  11448   3630] 0.6539096916299559
18 [667114  11457   3605] 0.6584419184918214
19 [667052  11464   3660] 0.6485527034407428
20 [666801  11457   3918] 0.6058673469387755
21 [666535  11460   4181] 0.5677743246473823
22 [666743  11456   3977] 0.5968836391053028
23 [666792  11457   3927] 0.6044795113260372
24 [666722  11452   4002] 0.5935548338745941
25 [666809  11447   3920] 0.6059678653404744
26 [666790  11437   3949] 0.6015189873417721
27 [666869  11460   3847] 0.6170433878929592
28 [666906  11455   3815] 0.6222164003143831
29 [666858  11466   3852] 0.6162428645563052
30 [666887  11470   3819] 0.6215650353310652
31 [666933  11480   3763] 0.6308100929614874
32 [666981  11477   3718] 0.6384408602150538
33 [667052  11472   3652] 0.6499726327312534
34 [667053  11466   3657] 0.6490844493030883
35 [667098  11448   3630] 0.6539096916299559
36 [667114

28 [520902 154312   6962]
29 [522033 153309   6834]
30 [523098 152341   6737]
31 [524169 151349   6658]
32 [525225 150348   6603]
33 [526227 149384   6565]
34 [527270 148399   6507]
35 [528329 147400   6447]
36 [529361 146419   6396]
37 [530400 145446   6330]
38 [531484 144447   6245]
39 [532511 143442   6223]
40 [533476 142457   6243]
41 [534470 141459   6247]
42 [535491 140450   6235]
43 [536592 139432   6152]
44 [537723 138356   6097]
45 [538753 137340   6083]
46 [539896 136250   6030]
47 [541048 135133   5995]
48 [542163 134049   5964]
49 [543488 132872   5816]
50 [544634 131745   5797]
51 [545837 130511   5828]
52 [546998 129317   5861]
53 [548208 128075   5893]
54 [549478 126790   5908]
55 [550815 125514   5847]
56 [552218 124144   5814]
57 [553609 122782   5785]
58 [555121 121286   5769]
59 [556656 119753   5767]
60 [558211 118230   5735]
61 [559866 116569   5741]
62 [561581 114835   5760]
63 [563344 113032   5800]
64 [565246 111039   5891]
65 [567171 109078   5927]
66 [569293 1

In [9]:
data_path = '/home/pico/uni/romi/scanner_cube/arabidopsis_im_bigger/204'
#print('count_rand: mean ',np.mean(count_rand,axis=0), ' std ',np.std(count_rand,axis=0) )
#print('count_uni', np.mean(count_uni,axis=0), ' std ',np.std(count_uni,axis=0) )
#print('count_all',count_all)

count_rand,dist_rand = test_random(data_path,10)
count_uni, dist_uni = test_uniform(data_path,10)
count_all = test_all(data_path)

print('count_rand',np.mean(count_rand,axis=0),np.mean(dist_rand))
print('count_uni', np.mean(count_uni,axis=0),np.mean(dist_uni))
print('count_all',count_all)

[569759  12331 100086] 0.5096507352941176
[570652  12484  99040] 0.514849286305546
[486856  12483 182837] 0.2789143547760843
[568355  12580 101241] 0.5037033379419317
[520770  13980 147426] 0.3458982149639195
[566330  12217 103629] 0.4921414443533214
[546350  12398 123428] 0.41317326463988596
[569848  17776  94552] 0.5393465158083959
[563192  15249 103735] 0.49158112862030745
[588041  15283  78852] 0.6466471416073941
[534124  12415 135637] 0.37595736368394284
[558472  13234 110470] 0.4617619638121272
[568304  12234 101638] 0.5017214582226681
[482303  13074 186799] 0.2730606170909792
[517172  11882 153122] 0.3330329624405788
[417911  21112 243153] 0.20978348035284683
[569691  16582  95903] 0.5317021808932071
[523201  11823 147152] 0.34654218815823445
[490864  13194 178118] 0.28639678431680765
[508931  14332 158913] 0.3209732831632332
[559555  12177 110444] 0.46171185443353097
[483131  15183 183862] 0.2774430038287504
[562510  12946 106720] 0.47780629930111856
[509287  14599 158290] 0.32

14 [564394  11477 106305] 0.47979645967757106
15 [569195  11472 101509] 0.5023737294145457
16 [563781  11466 106929] 0.4769002047704981
17 [566481  11448 104247] 0.48916723412009555
18 [577479  11457  93240] 0.5469011366073343
19 [581581  11464  89131] 0.5721256309590578
20 [588981  11457  81738] 0.6238212306901992
21 [594768  11460  75948] 0.6713659519014334
22 [589700  11456  81020] 0.6293280027639989
23 [581299  11457  89420] 0.5702593917710197
24 [575997  11452  94727] 0.5383827828968895
25 [569987  11447 100742] 0.5062426804819469
26 [567203  11437 103536] 0.49262667915672775
27 [561342  11460 109374] 0.466361932623303
28 [557640  11455 113081] 0.4511008930939959
29 [557032  11466 113678] 0.44873204500074765
30 [559851  11470 110855] 0.46015839226439603
31 [561691  11480 109005] 0.4679404858002495
32 [564394  11477 106305] 0.47979645967757106
33 [569195  11472 101509] 0.5023737294145457
34 [563781  11466 106929] 0.4769002047704981
35 [566481  11448 104247] 0.48916723412009555
36 [

26 [454343 156291  71542]
27 [455648 155276  71252]
28 [457026 154312  70838]
29 [458315 153309  70552]
30 [459779 152341  70056]
31 [461098 151349  69729]
32 [462475 150348  69353]
33 [463762 149384  69030]
34 [464990 148399  68787]
35 [466205 147400  68571]
36 [467344 146419  68413]
37 [468703 145446  68027]
38 [469766 144447  67963]
39 [470850 143442  67884]
40 [471952 142457  67767]
41 [473121 141459  67596]
42 [474103 140450  67623]
43 [475434 139432  67310]
44 [476627 138356  67193]
45 [477827 137340  67009]
46 [479084 136250  66842]
47 [480364 135133  66679]
48 [481478 134049  66649]
49 [482679 132872  66625]
50 [483871 131745  66560]
51 [485160 130511  66505]
52 [486500 129317  66359]
53 [487834 128075  66267]
54 [489318 126790  66068]
55 [490677 125514  65985]
56 [492248 124144  65784]
57 [493772 122782  65622]
58 [495382 121286  65508]
59 [496986 119753  65437]
60 [498389 118230  65557]
61 [499528 116569  66079]
62 [502378 114835  64963]
63 [503704 113032  65440]
64 [505030 1

In [10]:
data_path = '/home/pico/uni/romi/scanner_cube/arabidopsis_im_bigger/203'
#print('count_rand: mean ',np.mean(count_rand,axis=0), ' std ',np.std(count_rand,axis=0) )
#print('count_uni', np.mean(count_uni,axis=0), ' std ',np.std(count_uni,axis=0) )
#print('count_all',count_all)

count_rand,dist_rand = test_random(data_path,10)
count_uni, dist_uni = test_uniform(data_path,10)
count_all = test_all(data_path)

print('count_rand',np.mean(count_rand,axis=0),np.mean(dist_rand))
print('count_uni', np.mean(count_uni,axis=0),np.mean(dist_uni))
print('count_all',count_all)

[662611  13732   5833] 0.5678038745071147
[663653  13017   5506] 0.6015256084271704
[655580  20596   6000] 0.552
[663762  12586   5828] 0.5682910089224433
[664739  12292   5145] 0.643731778425656
[664918  12267   4991] 0.663594470046083
[663183  13219   5774] 0.5736058191894701
[661395  14876   5905] 0.5608806096528366
[664559  12264   5353] 0.618718475621147
[665046  11857   5273] 0.628105442821923
[662623  13717   5836] 0.5675119945167924
[663457  12535   6184] 0.535575679172057
[662834  13955   5387] 0.6148134397623909
[665625  11736   4815] 0.6878504672897197
[661519  14473   6184] 0.535575679172057
[664567  12219   5390] 0.6144712430426716
[663709  12616   5851] 0.5660570842591011
[662993  13528   5655] 0.5856763925729443
[664413  12454   5309] 0.6238462987379921
[664493  12435   5248] 0.6310975609756098
[665006  12088   5082] 0.6517119244391971
[665170  12150   4856] 0.6820428336079077
[663935  12631   5610] 0.5903743315508021
[663773  12827   5576] 0.593974175035868
[663218  135

16 [666045  11466   4665] 0.7099678456591639
17 [666086  11448   4642] 0.7134855665661353
18 [666097  11457   4622] 0.7165729121592385
19 [666068  11464   4644] 0.7131782945736435
20 [666054  11457   4665] 0.7099678456591639
21 [666062  11460   4654] 0.7116458960034379
22 [666059  11456   4661] 0.7105771293713795
23 [666163  11457   4556] 0.7269534679543459
24 [666124  11452   4600] 0.72
25 [666128  11447   4601] 0.7198435122799391
26 [666083  11437   4656] 0.711340206185567
27 [666053  11460   4663] 0.7102723568518121
28 [666034  11455   4687] 0.7066353744399403
29 [665974  11466   4736] 0.6993243243243243
30 [666005  11470   4701] 0.7045309508615188
31 [666016  11480   4680] 0.7076923076923077
32 [665990  11477   4709] 0.7033340411977065
33 [666017  11472   4687] 0.7066353744399403
34 [666045  11466   4665] 0.7099678456591639
35 [666086  11448   4642] 0.7134855665661353
36 [666097  11457   4622] 0.7165729121592385
37 [666068  11464   4644] 0.7131782945736435
38 [666054  11457   4665]

38 [530077 144447   7652]
39 [531260 143442   7474]
40 [532415 142457   7304]
41 [533588 141459   7129]
42 [534741 140450   6985]
43 [535891 139432   6853]
44 [537088 138356   6732]
45 [538209 137340   6627]
46 [539400 136250   6526]
47 [540623 135133   6420]
48 [541814 134049   6313]
49 [543098 132872   6206]
50 [544303 131745   6128]
51 [545633 130511   6032]
52 [546907 129317   5952]
53 [548213 128075   5888]
54 [549577 126790   5809]
55 [550925 125514   5737]
56 [552366 124144   5666]
57 [553790 122782   5604]
58 [555361 121286   5529]
59 [556973 119753   5450]
60 [558572 118230   5374]
61 [560295 116569   5312]
62 [562091 114835   5250]
63 [563937 113032   5207]
64 [566001 111039   5136]
65 [568017 109078   5081]
66 [570301 106855   5020]
67 [572958 104280   4938]
68 [575503 101809   4864]
69 [578082  99301   4793]
70 [581318  96127   4731]
71 [584284  93223   4669]
72 [587787  89771   4618]
73 [591450  86160   4566]
74 [595413  82252   4511]
75 [599744  77991   4441]
76 [604413  

In [11]:
data_path = '/home/pico/uni/romi/scanner_cube/arabidopsis_im_bigger/201'
#print('count_rand: mean ',np.mean(count_rand,axis=0), ' std ',np.std(count_rand,axis=0) )
#print('count_uni', np.mean(count_uni,axis=0), ' std ',np.std(count_uni,axis=0) )
#print('count_all',count_all)

count_rand,dist_rand = test_random(data_path,10)
count_uni, dist_uni = test_uniform(data_path,10)
count_all = test_all(data_path)

print('count_rand',np.mean(count_rand,axis=0),np.mean(dist_rand))
print('count_uni', np.mean(count_uni,axis=0),np.mean(dist_uni))
print('count_all',count_all)

[639911  13902  28363] 0.2616789479251137
[652304  11808  18064] 0.4108724534986714
[648871  13847  19458] 0.3814369411039161
[650067  12532  19577] 0.3791183531695357
[652285  12059  17832] 0.41621803499327054
[649836  12281  20059] 0.37000847499875367
[650728  12253  19195] 0.38666319353998435
[646205  15413  20558] 0.3610273372896196
[652115  12144  17917] 0.4142434559357035
[647709  13238  21229] 0.34961609119600545
[645031  13383  23762] 0.31234744550122046
[646923  12889  22364] 0.3318726524771955
[651433  12611  18132] 0.40933156849768365
[650743  12308  19125] 0.388078431372549
[647006  14535  20635] 0.3596801550763266
[641000  14108  27068] 0.27419831535392347
[646042  13636  22498] 0.32989599075473375
[651739  11896  18541] 0.4003020333315355
[610711  22393  49072] 0.15124714704923378
[648024  16008  18144] 0.40906084656084657
[647338  12993  21845] 0.33975738155184254
[648971  12406  20799] 0.3568440790422617
[648638  12520  21018] 0.3531258920924921
[647123  13378  21675] 0

13 [653666  11480  17030] 0.4358191426893717
14 [653558  11477  17141] 0.4329969079983665
15 [653649  11472  17055] 0.4351802990325418
16 [653941  11466  16769] 0.4426024211342358
17 [654229  11448  16499] 0.4498454451784957
18 [654501  11457  16218] 0.45763965963743986
19 [654607  11464  16105] 0.4608506674945669
20 [654701  11457  16018] 0.4633537270570608
21 [654728  11460  15988] 0.46422316737553165
22 [654582  11456  16138] 0.45990829099020947
23 [654474  11457  16245] 0.4568790397045245
24 [654378  11452  16346] 0.45405603817447693
25 [654391  11447  16338] 0.45427836944546457
26 [654379  11437  16360] 0.4536674816625917
27 [654027  11460  16689] 0.44472406974653966
28 [653943  11455  16778] 0.44236500178805577
29 [653870  11466  16840] 0.44073634204275536
30 [653838  11470  16868] 0.4400047427080863
31 [653666  11480  17030] 0.4358191426893717
32 [653558  11477  17141] 0.4329969079983665
33 [653649  11472  17055] 0.4351802990325418
34 [653941  11466  16769] 0.4426024211342358
35

22 [478395 160367  43414]
23 [480861 159275  42040]
24 [483107 158168  40901]
25 [484998 157308  39870]
26 [487031 156291  38854]
27 [489055 155276  37845]
28 [491040 154312  36824]
29 [492989 153309  35878]
30 [494839 152341  34996]
31 [496632 151349  34195]
32 [498498 150348  33330]
33 [500351 149384  32441]
34 [502230 148399  31547]
35 [504112 147400  30664]
36 [505915 146419  29842]
37 [507697 145446  29033]
38 [509438 144447  28291]
39 [511061 143442  27673]
40 [512654 142457  27065]
41 [514243 141459  26474]
42 [515759 140450  25967]
43 [517283 139432  25461]
44 [518810 138356  25010]
45 [520272 137340  24564]
46 [521768 136250  24158]
47 [523355 135133  23688]
48 [524867 134049  23260]
49 [526480 132872  22824]
50 [527970 131745  22461]
51 [529601 130511  22064]
52 [531226 129317  21633]
53 [532857 128075  21244]
54 [534562 126790  20824]
55 [536248 125514  20414]
56 [538075 124144  19957]
57 [539953 122782  19441]
58 [541970 121286  18920]
59 [543969 119753  18454]
60 [545947 1